esphome:
  name: clawd-pager-epaper
  friendly_name: "Clawd Pager (ePaper)"
  on_boot:
    priority: -10
    then:
      - logger.log: "🦞 Clawd Pager ePaper booting..."
      - text_sensor.template.publish:
          id: pager_display
          state: "READY"
      - text_sensor.template.publish:
          id: display_mode
          state: "DASHBOARD"
      - delay: 2s
      - logger.log: "Triggering initial display update..."
      - component.update: epaper_display
      - logger.log: "✅ Display update complete"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: recommended

# I2C Bus for RTC (PCF85063), PMIC (ETA6098), Audio Codec (ES8311)
# TODO: Find correct I2C pins from schematic (GPIO9 conflicts with EPD_BUSY)
# i2c:
#   sda: GPIO8   # Common ESP32-S3 I2C SDA
#   scl: GPIO9   # Common ESP32-S3 I2C SCL (CONFLICTS with EPD_BUSY!)
#   scan: true
#   frequency: 400kHz

# Real-Time Clock (PCF85063) - requires I2C
# TODO: Re-enable after finding correct I2C pins
# time:
#   - platform: pcf85063
#     id: rtc_time
#     timezone: America/New_York
#     update_interval: 60s

# ePaper Display (200x200 pixels)
# Pins verified from Waveshare ESP32-S3-ePaper-1.54 schematic
spi:
  clk_pin: GPIO13   # EPD_SCLK
  mosi_pin: GPIO14  # EPD_SDI (MOSI)
  id: epaper_spi

display:
  - platform: waveshare_epaper
    id: epaper_display
    # Waveshare ESP32-S3 1.54inch e-Paper (200×200, Black/White)
    # Controller: SSD1681
    model: 1.54in
    spi_id: epaper_spi
    cs_pin: GPIO12    # EPD_CS
    dc_pin: GPIO11    # EPD_D/C
    reset_pin: GPIO10 # EPD_RST
    busy_pin: GPIO9   # EPD_BUSY
    rotation: 0
    update_interval: 60s  # Reduced frequency to save power
    full_update_every: 30  # Prevent ghosting
    lambda: |-
      // Minimal test - just text, no sensors
      it.fill(COLOR_OFF);
      it.rectangle(0, 0, 200, 200);
      it.printf(100, 100, id(font_large), TextAlign::CENTER, "CLAWD");

# WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  
  ap:
    ssid: "Clawd-Pager-ePaper"
    password: "lobster2024"

# API for ESPHome connection
api:
  encryption:
    key: !secret api_key
  services:
    - service: show_message
      variables:
        message: string
        mode: string
      then:
        - text_sensor.template.publish:
            id: pager_display
            state: !lambda 'return message;'
        - text_sensor.template.publish:
            id: display_mode
            state: !lambda 'return mode;'
        - component.update: epaper_display
    
    - service: refresh_display
      then:
        - logger.log: "Manual display refresh requested"
        - component.update: epaper_display

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: VERBOSE  # Maximum logging to diagnose display issues
  logs:
    component: DEBUG
    display: VERBOSE

# Fonts optimized for ePaper readability
font:
  - file: "gfonts://Roboto Mono"
    id: font_small
    size: 12
    glyphs: "!\"#%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~ °"
  
  - file: "gfonts://Roboto Mono"
    id: font_medium
    size: 16
    glyphs: "!\"#%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~ °"
  
  - file: "gfonts://Roboto Mono"
    id: font_large
    size: 24

# Sensors for dashboard
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_rssi
    update_interval: 60s
  
  # Placeholder for battery (adjust based on PMIC ETA6098)
  - platform: template
    name: "Battery Percent"
    id: battery_percent
    unit_of_measurement: "%"
    accuracy_decimals: 0
    lambda: 'return 85.0;'  # TODO: Read from PMIC

text_sensor:
  - platform: wifi_info
    ssid:
      name: "WiFi SSID"
      id: wifi_ssid
    ip_address:
      name: "WiFi IP"
      id: wifi_ip
  
  - platform: template
    name: "Pager Display"
    id: pager_display
    
  - platform: template
    name: "Display Mode"
    id: display_mode
