esphome:
  name: clawd-pager
  friendly_name: "Clawd Pager"
  on_boot:
    priority: -10
    then:
      - rtttl.play: "Startup:d=4,o=5,b=180:c,e,g,c6"

esp32:
  board: m5stick-c
  framework:
    type: arduino

external_components:
  - source: github://martydingo/esphome-axp192
    components: [axp192]

i2c:
  id: bus_a
  sda: 21
  scl: 22
  scan: false

logger:
  level: DEBUG

api:
  encryption:
    key: "AoB3jpN0iVhstcEULCY9ESHY9WoArEH/4qFvlw2ckTs="

ota:
  - platform: esphome

wifi:
  ssid: "FlyingChanges"
  password: "flyingchanges"
  fast_connect: true
  power_save_mode: none

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/New_York"

output:
  - platform: ledc
    id: buzzer_pwm
    pin: GPIO2

rtttl:
  output: buzzer_pwm
  id: buzzer

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_sig
    update_interval: 10s
  - platform: axp192
    model: M5STICKC
    address: 0x34
    i2c_id: bus_a
    update_interval: 30s
    battery_level:
      name: "Battery Level"
      id: battery_level

  - platform: homeassistant
    id: ha_sun
    entity_id: sun.sun
    internal: true

text_sensor:
  - platform: homeassistant
    id: ha_message
    entity_id: input_text.clawd_status
    on_value:
      then:
        - rtttl.play: "Notify:d=4,o=6,b=200:c,e,g"

binary_sensor:
  - platform: gpio
    pin: { number: GPIO39, inverted: true }
    name: "Button B"
    on_press:
      then:
        - rtttl.play: "Blip:d=32,o=6,b=100:e"
        - homeassistant.service:
            service: input_text.set_value
            data:
              entity_id: input_text.clawd_status
              value: "Button B Pressed!"
  - platform: gpio
    pin: { number: GPIO37, inverted: true }
    name: "Button A"
    on_press:
      then:
        - rtttl.play: "Blip:d=32,o=6,b=100:c"
        - homeassistant.service:
            service: input_text.set_value
            data:
              entity_id: input_text.clawd_status
              value: "Button A (M5) Pressed!"

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

display:
  - platform: st7789v
    id: my_display
    model: TTGO_TDisplay_135x240
    cs_pin: GPIO5
    dc_pin: GPIO23
    reset_pin: GPIO18
    rotation: 270
    update_interval: 1s
    lambda: |-
      auto color_cyan = Color(0x00FFFF);
      auto color_green = Color(0x00FF00);
      auto color_white = Color(0xFFFFFF);
      auto color_grey = Color(0x333333);
      auto color_yellow = Color(0xFFFF00);

      it.fill(Color::BLACK);
      it.line(0, 20, 240, 20, color_cyan);
      
      if (id(sntp_time).now().is_valid()) {
        it.strftime(5, 3, id(font_small), color_cyan, TextAlign::TOP_LEFT, "%H:%M:%S", id(sntp_time).now());
      }

      if (id(ha_message).has_state()) {
        it.print(120, 3, id(font_small), color_green, TextAlign::TOP_CENTER, "SYNCED");
      } else if (id(ha_sun).has_state()) {
        it.print(120, 3, id(font_small), color_yellow, TextAlign::TOP_CENTER, "API OK");
      } else {
        it.print(120, 3, id(font_small), color_grey, TextAlign::TOP_CENTER, "WAITING");
      }

      it.printf(235, 3, id(font_small), color_cyan, TextAlign::TOP_RIGHT, "%.0f%%", id(battery_level).state);

      if (id(ha_message).has_state()) {
        it.print(120, 65, id(font_body), color_white, TextAlign::CENTER, id(ha_message).state.c_str());
      } else {
        it.print(120, 65, id(font_body), color_yellow, TextAlign::CENTER, "Connecting...");
      }

      it.line(0, 115, 240, 115, color_grey);
      int rssi = id(wifi_sig).state;
      it.printf(5, 120, id(font_small), color_grey, TextAlign::TOP_LEFT, "WIFI: %d dBm", rssi);
      
      float uptime = millis() / 1000.0;
      it.printf(235, 120, id(font_small), color_grey, TextAlign::TOP_RIGHT, "%.0fs", uptime);

font:
  - file: "gfonts://Roboto Mono"
    id: font_body
    size: 16
  - file: "gfonts://Roboto Mono"
    id: font_small
    size: 12
